[package]
name = "firewheel-sampler"
version = "0.1.0"
description = "Sampler nodes for the Firewheel audio engine"
homepage = "https://github.com/BillyDM/firewheel/blob/main/crates/firewheel-sampler"
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
bevy_ecs = ["dep:bevy_ecs"]

[dependencies]
firewheel-core = { path = "../firewheel-core", version = "0.1" }
firewheel-graph = { path = "../firewheel-graph", version = "0.1" }
smallvec.workspace = true
arrayvec.workspace = true
crossbeam-utils.workspace = true
log.workspace = true
bevy_ecs = { version = "0.15", optional = true }

